version: '3.8'

services:
  stream-server-camera:
    image: stream-server
    command: --url rtsp://host.docker.internal:8554/camera
    ports:
      - "8081:8080"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Soporte para Linux (Docker 20.10+)

  stream-server-thermal:
    image: stream-server
    command: --url rtsp://host.docker.internal:8554/thermal
    ports:
      - "8082:8080"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
